### PR TITLE
Fixes #7 by allowing web components to have children (for ex buttons)

### LINKED ISSUE #7: How to send children prop in the custom HTML element created
Let say I want something inside the `<text-x> Hi </text-x>`, I tried using `<text-x children="Hi"></text-x>` both didn't work

### PR DESCRIPTION
**Pull request by halkeye**

### CODE REVIEW

**Comment by halkeye** [comment]
https://github.com/remarkablemark/html-react-parser with node.innerHTML would be another option

**Comment by halkeye** [comment]
pinging @cherifGsoul as they don't seem to be watching the repo but did the recent commits.

**Comment by cherifGsoul** [comment]
@halkeye Thank you for the PR, we will review it and get back to you ASAP.

**Comment by halkeye** [comment]
so the more i look into this, the less I'm certain it'll work. It seems to work on firefox, but children and childNodes both return nothing on first connect with chrome

I think https://stackoverflow.com/questions/54369528/how-to-use-a-custom-element-to-wrap-child-custom-elements-into-a-div is related

**Comment by justinbmeyer** [comment]
Ah, I think I see what you are going for.  It seems like `<slot>` has decent support: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/slot

**Comment by justinbmeyer** [comment]
I suppose the problem is that the react code needs `.children` immediately upon rendering ...

I wonder if there's a way to know when the DOM has completed all children of the webcomponent.

I think https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/slotchange_event might be a way to do that ...

We could render the `<slot>` and listen to it's `slotchange`.  Only after this event fires could we render react with children.

How to know if the slot wasn't filled?  I'm not sure about that ...

**Comment by justinbmeyer** [comment]
Slots fire on the next microtask: https://salesforce.stackexchange.com/questions/260305/lwc-check-if-slot-is-empty/260545

> In this case, you should rely on the slotchange event. This event fires when the slot assigned node changes in the next microtask.

**Comment by halkeye** [comment]
So I have a solution (just been testing with real data) that works when you add <script> after your elements instead of before. I'll be updating this PR in a few min.

How would slot works? I've never actually used them before.

I'm trying to make <do-button>Foo</do-button> work, but if <do-button><slot>foo</slot></do-button> is the solution, its not that far fetched

**Comment by justinbmeyer** [comment]
It looks like you can see the assigned nodes immediately with:

```
console.log("assigned", slot. assignedNodes().length )
```

I'll write up a rough idea on how it could work ...

**Comment by justinbmeyer** [comment]
`<slots>` are more or less the web-component way of doing what react is doing with `props.children`.

To make this work, I think we'd want to render a `<slot>` in the shadow root.


```
this.attachShadow({mode: 'open'});
this.shadowRoot.innerHTML = `<slot></slot>`;
```

Then I think you can access any assigned nodes:

```js
const slot = this.shadowRoot.querySelector('slot');
const nodes = slot.assignedNodes()
```

Hopefully you can run those through `mapChildren` and everything will work.  

I'm not sure how this will interact with people who wanted to render to shadow dom.  This might be incompatible.

**Comment by christopherjbaker** [comment]
Closing as inactive. We have started this work on our own.

**Pull request closed without merging**
